### ISSUE TITLE
Missing upstream commit 736985?

### ISSUE THREAD

**Issue by wsxy162** [ArrowOS/android_packages_apps_Settings#3]
I have facing this [issue](https://issuetracker.google.com/issues/111161680), and the fix was submited a half year ago -- [Gerrit Code Review](https://android-review.googlesource.com/c/platform/packages/apps/Settings/+/736985/).
Have ArrowOS merged this commit already?

**Comment by Bauuuuu** [comment]
https://review.arrowos.net/c/ArrowOS/android_packages_apps_Settings/+/4360 
we have picked up it now! will be available soon in the source
Thanks for report
